version: '3.8'

services:
  service-voucher-campaign:
    container_name: app
    build:
      context: .
      target: prod
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_PORT: 3000
      POSTGRESQL_HOST: db
      POSTGRESQL_PORT: 5432
      POSTGRESQL_USER: root
      POSTGRESQL_PASSWORD: root
      POSTGRESQL_DATABASE: service_voucher_campaign
  db:
    container_name: db
    image: postgres:13.10
    ports:
      - 5432:5432
    volumes:
      - data:/data/db
    environment:
      POSTGRES_DB: service_voucher_campaign
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d service_voucher_campaign -U root"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data: {}
